### ISSUE TITLE
Error Encountered While Installing Burp Suite Nuclei Templates Generators Extension

### ISSUE THREAD

**Issue by Jeetu-study** [projectdiscovery/nuclei-burp-plugin#122] opened 2024-09-25 05:37 UTC
Hi Team,

I am facing an issue while installing the Burp Suite Nuclei Templates Generators extension. The error log is as follows:

[11:05:20] Error while trying to initialize the plugin:
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "definitions" is null
	at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:127)
	at io.projectdiscovery.nuclei.util.SchemaUtils.yamlFieldDescriptionTransformer(SchemaUtils.java:108)
	at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:61)
	at burp.BurpExtender.initializeNucleiYamlSchema(BurpExtender.java:81)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:71)
	at burp.Zt9h.ZW(Unknown Source)
	at burp.Zlzu.ZH(Unknown Source)
	at burp.Zlz3.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

I have tried installing the extension on different systems, but the issue persists. I have also attached a screenshot of the error for your reference.
Could you please help resolve this issue so that I can successfully install and use this extension?

<img width="960" alt="image" src="https://github.com/user-attachments/assets/655b0b21-e6f0-416f-9a4d-1ae6b9e2caad">

**Comment by forgedhallpass** [comment] 2024-09-25 21:43
Duplicate of #115

**Closed as not planned by forgedhallpass** 2024-09-25 21:43 UTC
