### ISSUE TITLE
path err when i save my template

### ISSUE THREAD

**Issue by LuoooB** [projectdiscovery/nuclei-burp-plugin#81] opened 2023-10-23 09:34 UTC
![image](https://github.com/projectdiscovery/nuclei-burp-plugin/assets/40429942/c3152991-033f-401a-b532-a6303251b83e)

**Comment by forgedhallpass** [comment] 2023-10-23 16:07
@LuoooB this has been fixed, but might not have been officially released.
Please try building the latest version of the code and use that.

It should be duplicate of: #40

**Comment by dogancanbakir** [comment] 2023-10-24 12:40
Closing this. As stated by @forgedhallpass, this is a duplicate of #40.

**Closed by dogancanbakir** 2023-10-24 12:40 UTC
